version: "3"

services:
  lb:
    image: haproxy
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3
      - nodeapp4
      - nodeapp5
      - nodeapp6
      - nodeapp7
      - nodeapp8
  nodeapp1:
    image: http
    environment:
      - PORT=3001
  nodeapp2:
    image: http
    environment:
      - PORT=3002
  nodeapp3:
    image: http
    environment:
      - PORT=3003
  nodeapp4:
    image: http
    environment:
      - PORT=3004
  nodeapp5:
    image: http
    environment:
      - PORT=3005
  nodeapp6:
    image: http
    environment:
      - PORT=3006
  nodeapp7:
    image: http
    environment:
      - PORT=3007
  nodeapp8:
    image: http
    environment:
      - PORT=3008

  # nodeapp11:
  #   image: http
  #   environment:
  #     - PORT=3011
  # nodeapp12:
  #   image: http
  #   environment:
  #     - PORT=3012
  # nodeapp13:
  #   image: http
  #   environment:
  #     - PORT=3013
  # nodeapp14:
  #   image: http
  #   environment:
  #     - PORT=3014
  # nodeapp15:
  #   image: http
  #   environment:
  #     - PORT=3015
  # nodeapp16:
  #   image: http
  #   environment:
  #     - PORT=3016
  # nodeapp17:
  #   image: http
  #   environment:
  #     - PORT=3017
  # nodeapp18:
  #   image: http
  #   environment:
  #     - PORT=3018
