version: "3"

services:
  lb:
    image: haproxy
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3
      - nodeapp4
      - nodeapp5
      - nodeapp6
      - nodeapp7
      - nodeapp8
  nodeapp1:
    image: simple
    environment:
      - PORT=3001
  nodeapp2:
    image: simple
    environment:
      - PORT=3002
  nodeapp3:
    image: simple
    environment:
      - PORT=3003
  nodeapp4:
    image: simple
    environment:
      - PORT=3004
  nodeapp5:
    image: simple
    environment:
      - PORT=3005
  nodeapp6:
    image: simple
    environment:
      - PORT=3006
  nodeapp7:
    image: simple
    environment:
      - PORT=3007
  nodeapp8:
    image: simple
    environment:
      - PORT=3008
